ldelossa/gh.nvim

- lua/litee/gh/commands.lua
- lua/litee/gh/ghcli/graphql.lua
- lua/litee/gh/ghcli/init.lua
- lua/litee/gh/pr/diff_view.lua
- lua/litee/gh/pr/init.lua
- lua/litee/gh/pr/thread_buffer.lua
this commit adds the previewing of the lines where a thread occurs
along with allowing multiline threads to be created both in and outside
of review.
Signed-off-by: ldelossa <louis.delos@gmail.com>
> feat: add thread preview and multiline comments

- lua/litee/gh/pr/details.lua
- lua/litee/gh/pr/files_changed.lua
- lua/litee/gh/pr/handlers.lua
- lua/litee/gh/pr/init.lua
- lua/litee/gh/pr/marshal.lua
- lua/litee/gh/pr/state.lua
this commit adds a new "Files Changed" root to the pr tree.
this was due to popular demand as many users wanted both a HUD of
changed files and a commit-wise view of changes.
> feat: aggregated file view

- README.md
The help page has extensive setup information, but some users just want to copy/paste code from the readme to setup, so I pulled some information from the help page onto the readme.
I also spent some time on some which key bindings for all the commands and figured that would be useful for others as well.
> Add setup info to README.md

- lua/litee/gh/gitcli/init.lua
- lua/litee/gh/pr/diff_view.lua
- lua/litee/gh/pr/handlers.lua
- lua/litee/gh/pr/state.lua
this commit wires in some commit checks when doing a refresh to discern
if a squash or rebase occured.
if it does the repo is reset to its origin via `git reset --hard
{remote}/{branch}`
if the repository is dirty (you have made changes to some code under
review) the refresh will fail and ask you to stash them, keeping any
changes you've made while reviewing in place.
Signed-off-by: ldelossa <louis.delos@gmail.com>
> useability: handle rebases

- lua/litee/gh/init.lua
The refresh timer is started automatically after `require('litee.gh').setup({...})`, which is called on neovim startup for most users. It seems unneccessary to bother the user with information about the refresh timer.
This PR resolves #40.
> fix: remove unnecessary message on gh.nvim startup

- lua/litee/gh/commands.lua
- lua/litee/gh/ghcli/init.lua
- lua/litee/gh/issues/init.lua
- lua/litee/gh/pr/init.lua
Introduces two re-worked commands "GHSearchPRs" and "GHSearchIssues".
When issued a vim.ui.input prompt is issued where a query string can be
inputted.
For PRs this query string is also constrained by "repo:{owner}/{repo}"
to ensure PRs from other repositories are not opened.
For issues, this constraint does not exist so you can search issues
cross repository for referencing/searching issues which reside elsewhere
but are related to your current repo.
Closes: #43
Signed-off-by: ldelossa <louis.delos@gmail.com>
> feat: implement proper issue and pr searching

- lua/litee/gh/commands.lua
- lua/litee/gh/ghcli/init.lua
- lua/litee/gh/init.lua
- lua/litee/gh/issues/preview.lua
- lua/litee/gh/notifications/init.lua
- lua/litee/gh/notifications/notifications_buffer.lua
- lua/litee/gh/pr/init.lua
- lua/litee/gh/pr/thread_buffer.lua
This feature introduces the "GHNotifications" command.
This command will open a new buffer which lists the notifications for
the given repository Neovim is opened to.
From there you can open PRs and issues which the notifications
reference.
By setting a notification as "read" it will be removed from the buffer
view. By setting it to "unsubscribed" it will be removed and any further
non-mention comments will be ignored.
> feat: "GHNotifications" - implement a notifications buffer

- lua/litee/gh/issues/init.lua
Hi @ldelossa, I've been using your plugin for a couple of days.
And I've noticed I get a `Failed to fetch issue.` when my cursor is
on top of a comment.
---
The expression used to match the number was using an asterisk, which
matches zero or more, instead of one or more.
We're also moving away from scanning the line in favor of expanding the
current WORD under the cursor, and extracting the number with lua,
instead of the internal vim functions.
> fix: false positives while reading issue/PR numbers

- lua/litee/gh/issues/init.lua
This is a follow up for #55.
Asserting the start of the line gets in the way of matching issue ids in
the issue buffer, which uses a border right next to the issue number.
For example, the following comment in `GHOpenIssue 55`:
```
│#53
```
> fix: loosen up issue number regex

- lua/litee/gh/commits/commit_buffer.lua
- lua/litee/gh/commits/init.lua
- lua/litee/gh/ghcli/init.lua
- lua/litee/gh/init.lua
- lua/litee/gh/pr/init.lua
conversations
the GitHub API allows conversations to happen on a per-commit basis.
Previous to this commit there was no way to comment and have a
conversation per commit.
Now, you can access a commit convo buffer but first opening a PR,
navigating to a commit in the PR, and then hitting (default) <CR> on the
root of the commit tree UI that subsequently opened.
This will open a new tab with the full commit message along with the
ability to comment on the commit.
This is also handy for very large commit messages which do not fit
within the detail popup window.
> feat,commit convo buffer: add a buffer for viewing commit messages and

- lua/litee/gh/pr/init.lua
Calling `:GH` and selecting `GHOpenPR` results in an error because the `open_pull(args)` function in `litee/gh/pr/init.lua` is called with null arguments. This PR adds a check to avoid the error.
> fix: check for args existence before accessing it

- doc/gh-nvm.txt
- lua/litee/gh/commits/commit_buffer.lua
- lua/litee/gh/config.lua
- lua/litee/gh/init.lua
- lua/litee/gh/issues/issue_buffer.lua
- lua/litee/gh/notifications/notifications_buffer.lua
- lua/litee/gh/pr/thread_buffer.lua
This PR moves away from using utf-8 icons as message separators and will use highlights instead.
This is more useful since wrapping works way better. There are no icons which can get wrapped incorrectly and make the output look screwed up. 
Two new highlights are added "GHThreadSep" and "GHThreadSepAlt" which allow for alternating message separators. 
Here is a screenshot of a message thread after this PR.
This PR sets both new highlights to a default of "Pmenu" if they are not defined.
> Use highlights as message separators

- doc/gh-nvm.txt
- doc/tags
- lua/litee/gh/commands.lua
- lua/litee/gh/config.lua
- lua/litee/gh/debug.lua
- lua/litee/gh/ghcli/init.lua
- lua/litee/gh/gitcli/init.lua
this commit adds a new config flag "debug_logging" and a new command
"GHOpenDebugBuffer".
when `debug_logging` is flipped to `true` in the user config passed to
setup(), all CLI interactions will be outputted into a debug buffer.
this debug buffer can be opened with the command "GHOpenDebugBuffer".
see doc/gh-nvim.txt for more details.
> feat,useability: introduce debug buffer for cli interactions

- lua/litee/gh/ghcli/graphql.lua
- lua/litee/gh/ghcli/init.lua
- lua/litee/gh/pr/diff_view.lua
- lua/litee/gh/pr/handlers.lua
- lua/litee/gh/pr/init.lua
- lua/litee/gh/pr/marshal.lua
- lua/litee/gh/pr/thread_buffer.lua
previous to this commit gh.nvim did not understand that a comment can
track its original commit sha
without this, it could not decipher which comments belonged to which
commits and would overrlay comments over multiple commits.
with these changes will now only display comments on a commit in the
commit tree view, checkout the commit and open the correct files when
using the Conversations: tab, and correctly sync review threads to their
commits during review.
additionally, a few UI elements have changed. the Conversations: tab in
the pr details tree now shows the commit a threaded conversation belongs
to. Also, an asterick is used in the Commits: tree now to indicate which
commit gh.nvim has currently checked out.
fixes: #47
Signed-off-by: Louis DeLosSantos <louis.delos@gmail.com>
> fix: fix review thread conflicts

- lua/litee/gh/pr/init.lua
As the title.
Under macOS `open` command is largely equivalent to `xdg-open` in Free
Desktop standard.
> feat: GHViewWeb uses "open" under macOS

- lua/litee/gh/pr/init.lua
Tested under both macOS and Linux (Xorg/KDE) this time :)
> feat: GHViewWeb uses "open" under macOS (reroll)

- lua/litee/gh/pr/diff_view.lua
- lua/litee/gh/pr/init.lua
- lua/litee/gh/pr/thread_buffer.lua
this commit removes any comment-to-commit-sha checking and instead
relies on matching the source code line the comment references to the
actual lines in a vim buffer.
Signed-off-by: Louis DeLosSantos <louis.delos@gmail.com>
> fix: perform source file matching for comment linking

- lua/litee/gh/ghcli/graphql.lua
- lua/litee/gh/ghcli/init.lua
- lua/litee/gh/pr/thread_buffer.lua
This fixes the single line comment during a review. It seems like on 2023-10-01 GH deprecated the `possiton` and `path` which is what was used to create a comment during a started review. It seems like [here](https://docs.github.com/en/graphql/reference/input-objects#addpullrequestreviewcommentinput) states to use `addPullRequestReviewThread` instead.
This addresses https://github.com/ldelossa/gh.nvim/issues/76 and possibly https://github.com/ldelossa/gh.nvim/issues/86
> When starting a review: creating a single line comment is broken

- lua/litee/gh/pr/diff_view.lua
Currently, in diff files, we use the parent commit of the first commit of the PR as the base ref for the diff view by files (!= commit).
When a PR is opened targeting a base branch (main), for a branch that is currently rebased on the target branch, the current diff for changed file is correct.
However, if the workflow is not to rebase on the base branch, but to merge the base branch into the PR branch, we see changes that are not included in the PR in the diff, because we are comparing with an old ref. This is because the parent commit of the first commit is an older commit of the base branch, so any change added to the base branch and merged into the target branch will be considered as part of the diff.
To mirror the diff we see on the web UI, using the sha from the pr data fixes this. …
> Use base sha from pr data in file diff view

- README.md
[lazy.nvim](https://github.com/folke/lazy.nvim) has quickly becoming the standard package manager.
I found this plugin to be less straightforward to install using it, so I thought I'd share my solution so that people don't give up before trying this cool plugin.
> docs: add lazy.nvim installation instruction

- doc/gh-nvm.txt
- lua/litee/gh/commands.lua
- lua/litee/gh/ghcli/graphql.lua
- lua/litee/gh/ghcli/init.lua
- lua/litee/gh/pr/buffer.lua
- lua/litee/gh/pr/diff_view.lua
- lua/litee/gh/pr/files_changed.lua
- lua/litee/gh/pr/marshal.lua
- lua/litee/gh/pr/state.lua
This pr queries the [pull request file viewed state](https://docs.github.com/en/graphql/reference/objects#pullrequestchangedfile) from github's graphql api, and displays a small check mark is the file has been marked as viewed.
Resolves #98
> Display checkmark icon in PR files if file is marked as viewed

- lua/litee/gh/pr/files_changed.lua
Files come in a random order from the [API](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files)
I propose we sort them before building the tree in order to have deterministic order on a PR, avoiding confusion.
This trick with the extra table is the simplest way I have found for a table in a sorted order by their index lua, let me know if I have missed a magical sort function.
> feat: sort filenames alphabetically in the files_changed tree

- lua/litee/gh/pr/state.lua
sometimes the base is not part of the branch anymore. In this case the reference is still provided in the information received by github.
This change fetches also this reference/sha to provide a diff view.
Fixes #108
> Fetch the "sha" of the base for PR

- lua/litee/gh/ghcli/init.lua
Commit d6afb4f61dc4 ("gh_exec uses extra args like async_request")
inadvertently introduced some malformed GitHub CLI commands by merging
multiple field parameters together. This would result in the following
runtime error when attempting to add a comment to a pending PR review:
```
E5108: Error executing lua: .../gh.nvim/lua/litee/gh/ghcli/init.lua:834: attempt to call a string value
stack traceback:
.../gh.nvim/lua/litee/gh/ghcli/init.lua:834: in function 'create_comment_review'
.../gh.nvim/lua/litee/gh/pr/thread_buffer.lua:740: in function 'create'
.../gh.nvim/lua/litee/gh/pr/thread_buffer.lua:842: in function <...ts/.vim/bundle/gh.nvim/lua/litee/gh/pr/thread_buffer.lua:823>
```
Fix it by introducing the necessary commas to separate the fields.
Fixes: d6afb4f61dc4 ("gh_exec uses extra …
> Fix review comment threads for pending reviews
